name: Deploy Via SSH
on: [push]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          script: cd /home/${{ secrets.USER }}/tophy-bot; git pull; ${{ secrets.NPM_BIN }}/yarn; ${{ secrets.NPM_BIN }}/pm2 reload "Tophy bot"
